on:
  schedule:
    - cron: '0 16 * * 3' # */5 * * * *
    
jobs:
  scrape-map:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
          
      - name: Install packages
        uses: r-lib/actions/setup-renv@v2
        
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Scrape and map
        run: Rscript -e 'source("Rscripts/forecast_map.R")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m 'weekly update' || echo "No changes to commmit"
          git push origin || echo "No changes to commit"
        